<?php
return [
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'Data_Type' => [
        "1" => 'Report Type 1',
        "2" => 'Report Type 2',
        "3" => 'Report Type 3',
        "4" => 'Report Type 4',
        "5" => 'Report Type 5',
        "6" => 'Report Type 6',
        "7" => 'Report Type 7',
    ],
    'Data_Fields' => [
        'innerId' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '仪器内部编码',
            'desc' => '所在单位仪器内部编码	仪器所在单位系统内部id，能唯一标识仪器',
            'support' => [1, 2, 3, 4],
        ],
        'canme' => [
            'type' => 'VARCHAR',
            'length' => 50,
            'label' => '仪器中心名称',
            'desc' => '科学仪器中心全称，不可简写（最多50字）',
            'support' => [1, 2, 3, 4],
        ],
        'ename' => [
            'type' => 'VARCHAR',
            'support' => [1, 2, 3, 4],
        ],
        'instrBelongsType' => [
            'type' => 'SELECT',
            'label' => '隶属关系',
            'desc' => '所属大型科学装置/仪器中心/服务单元	仪器设备所隶属的科学仪器中心',
            'values' => ['大型科学装置', '服务单元', '无'],
            'support' => [1, 2, 3, 4],
        ],
        'InstrBelongsName' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '隶属仪器所在单位仪器内部编号',
            'desc' => '确定隶属大型科学装置/仪器中心/服务单元唯一的一台仪器',
            'support' => [1, 2, 3, 4],
        ],
        'instrCategory' => [
            'type' => 'VARCHAR',
            'length' => 6,
            'label' => '设备分类编码',
            'desc' => '依据“大型科学仪器设备资源的建设与整合”平台建设项目的《大型科学仪器设备分类标准与编码规则（试用）》，按大类、中类、小类选择填写（6位数字代码）',
            'innerType' => 'number',
            'support' => [1, 2, 3, 4],
        ],
        'instrSource' => [
            'type' => 'SELECT',
            'label' => '仪器设备来源',
            'values' => ['购置', '研制', '赠送', '其他'],
            'support' => [1, 2, 3, 4],
        ],
        'instrSupervise' => [
            'type' => 'SELECT',
            'label' => '海关监管情况',
            'desc' => '仪器是否被海关监管，若仪器被海关监管，填写“是”，若仪器不被海关监管，填写“否”',
            'values' => ['是', '否'],
            'support' => [1, 2, 3, 4],
        ],
        'level' => [
            'type' => 'VARCHAR',
            'length' => 10,
            'label' => '仪器中心级别',
            'desc' => '国家级、省部级、地市级或单位级等（单选，以所属最高级别为准）',
            'values' => ['国家级', '省部级', '地市级', '单位级', 'other'],
            'support' => [1, 2, 3, 4],
        ],
        'url' => [
            'type' => 'URL',
            'length' => 100,
            'support' => [1, 2, 3, 4],
        ],
        'worth' => [
            'type' => 'FLOAT',
            'label' => '原值',
            'desc' => '科学装置的购置单价或研制成本，按资产登记价格填写。国产科学装置以人民币填报，进口科学装置根据建账时的汇率折合成人民币计算（单位为万元，保留2位小数），优惠价及赠送仪器按市场价或资产登记价格填写',
            'decimal' => 2,
            'unit' => '万元',
            'support' => [1, 2, 3, 4],
        ],
        'establish' => [
            'type' => 'DATE',
            'format' => 'yyyy-mm-dd',
            'support' => [1, 2, 3, 4],
        ],
        'nation' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '产地国别',
            'desc' => '科学装置的实际制造地所在国家或地区，按国家标准《世界各国和地区名称代码》（GB/T 2659-2000）选择填写，自主研发的填写中国；国家简称',
            'support' => [1, 2, 3, 4],
        ],
        'manufacturer' => [
            'type' => 'VARCHAR',
            'length' => 100,
            'label' => '生产制造商',
            'desc' => '仪器设备生产或设计制造单位的全称（非代理商），自主研发需填写本单位（最多100字）',
            'support' => [1, 2, 3, 4],
        ],
        'beginDate' => [
            'type' => 'DATE',
            'label' => '启用日期',
            'desc' => '科学装置投入使用的日期（按YYYY-MM-DD格式填写）',
            'format' => 'yyyy-mm-dd',
            'support' => [1, 2, 3, 4],
        ],
        'type' => [
            'type' => 'SELECT',
            'length' => 10,
            'label' => '科学仪器中心类别',
            'desc' => '通用或专用',
            'values' => ['通用', '专用'],
            'support' => [1, 2, 3, 4],
        ],
        'instrVersion' => [
            'type' => 'VARCHAR',
            'length' => 100,
            'label' => '规格型号',
            'desc' => '按仪器设备生产制造厂商的标识填写',
            'support' => [1, 2, 3, 4],
        ],
        'technical' => [
            'type' => 'TEXT',
            'length' => 500,
            'label' => '主要线站与仪器设备及技术指标',
            'desc' => '构成科学装置的核心线站、主要仪器设备的名称、型号以及能代表仪器设备主要技术性能的指标或参数',
            'support' => [1, 2, 3, 4],
        ],
        'function' => [
            'type' => 'TEXT',
            'length' => 300,
            'label' => '主要功能',
            'desc' => '对科学装置主要功能的简要介绍',
            'support' => [1, 2, 3, 4],
        ],
        'subject' => [
            'type' => 'VARCHAR',
            'length' => 200,
            'label' => '主要学科领域',
            'desc' => '按国家标准《学科分类与代码》（GB/T 13745-2009）选择填写仪器中心支持科技活动的主要学科名称，涉及多个学科领域的可多选（最多4个）（一级学科）\n如：化学，物理学',
            'support' => [1, 2, 3, 4],
        ],
        'serviceContent' => [
            'type' => 'VARCHAR',
            'length' => 200,
            'label' => '服务内容',
            'desc' => '科学仪器中心提供的各类服务项目描述，如样品测试、分析检测、技术咨询、认证服务等',
            'support' => [1, 2, 3, 4],
        ],
        'achievement' => [
            'type' => 'TEXT',
            'length' => 45,
            'label' => '服务的典型成果',
            'desc' => '列举该科学仪器中心面向社会提供服务、支撑重大项目或主要成果的典型案例（1-3个，没有可填写无）',
            'support' => [1, 2, 3, 4],
        ],
        'status' => [
            'type' => 'VARCHAR',
            'length' => 10,
            'label' => '运行状态',
            'desc' => '指科学装置当年通常技术性能状态，按正常、待机、远程服务中、偶有故障、故障频繁、待修、待报废选择填写（单选）。按科学装置当年一般状况下的运行状态填写，并非填报时的特定状态',
            'support' => [1, 2, 3, 4],
        ],
        'requirement' => [
            'type' => 'TEXT',
            'length' => 500,
            'label' => '对外开放共享规定',
            'desc' => '用户申请条件、申请方式、申请时间、申请流程、申请材料、服务时间安排等的方面的要求',
            'support' => [1, 2, 3, 4],
        ],
        'fee' => [
            'type' => 'TEXT',
            'length' => 500,
            'label' => '参考收费标准',
            'desc' => '对外开放相关收费标准，为用户提供服务时收取的费用，按照单位已有收费标准填写。是对仪器中心现有收费标准的概述，无需精确到每台仪器',
            'support' => [1, 2, 3, 4],
        ],
        'serviceUrl' => [
            'type' => 'VARCHAR',
            'length' => 150,
            'label' => '预约服务网址',
            'desc' => '管理单位在线服务平台提供的用户在线预约获取服务接口的URL，能够实现对本仪器中心仪器的预约申请',
            'support' => [1, 2, 3, 4],
        ],
        'province' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '详细地置 省',
            'desc' => '科学装置所在的详细地理位置 （自治区、直辖市）',
            'support' => [1, 2, 3, 4],
        ],
        'city' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '详细地置 市',
            'desc' => '科学装置所在的详细地理位置',
            'support' => [1, 2, 3, 4],
        ],
        'county' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '详细地置  区',
            'desc' => '科学装置所在的详细地理位置（县)',
            'support' => [1, 2, 3, 4],
        ],
        'street' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '详细地置 街道',
            'desc' => '科学装置所在的详细地理位置（乡镇，需包括街道/乡镇门牌号）',
            'support' => [1, 2, 3, 4],
        ],
        'contact' => [
            'type' => 'VARCHAR',
            'length' => 20,
            'label' => '联系人',
            'desc' => '联系人姓名',
            'support' => [1, 2, 3, 4],
        ],
        'phone' => [
            'type' => 'PHONE',
            'label' => '电话',
            'desc' => '座机（加区号）或手机，以联系人座机为主，一个电话号码即可',
            'support' => [1, 2, 3, 4],
        ],
        'email' => [
            'type' => 'EMAIL',
            'label' => '电子邮箱',
            'desc' => '联系人的电子邮箱',
            'support' => [1, 2, 3, 4],
        ],
        'address' => [
            'type' => 'VARCHAR',
            'length' => 100,
            'label' => '通讯地址',
            'desc' => '通讯地址',
            'support' => [1, 2, 3, 4],
        ],
        'postalcode' => [
            'type' => 'VARCHAR',
            'length' => 6,
            'label' => '邮政编码',
            'desc' => '联系人办公地址的邮政编码',
            'innerType' => 'number',
            'support' => [1, 2, 3, 4],
        ],
        'shareMode' => [
            'type' => 'SELECT',
            'label' => '共享模式',
            'values' => ['内部共享', '外部共享', '不共享'],
            'support' => [1, 2, 3, 4],
        ],
        'image' => [
            'type' => 'URL',
            'length' => 150,
            'label' => '仪器中心图片',
            'desc' => '科学仪器中心图片对应的URL（外网可以访问的图片url），图片要求1M字节以内，jpg格式',
            'support' => [1, 2, 3, 4],
        ],
        'auditStatus' => [
            'type' => 'SELECT',
            'label' => '提交状态',
            'desc' => '未提交，代表后期需要对数据进行重复报，更新完善数据；提交，代表报送的数据无误，后期无需更新完善。已经提交的数据，再次推送更新无效，需等待后期审核驳回再进行修改。\n如果因为失误提交，请等待国家平台审核驳回后更新',
            'values' => ['-1' => '未提交', '0' => '提交'],
            'showValue' => true,
            'support' => [1, 2, 3, 4],
        ],
    ],

];
