<?php
return [
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'Database_Type' => [
        'MySQL' => ['dsn' => 'mysql:host={host};dbname={dbname}',],
    ],
    'Data_Type' => [
        "1" => Yii::t('yii', '科学仪器中心'),
        "2" => Yii::t('yii', '大型科学装置'),
        "3" => Yii::t('yii', '科学仪器服务单元'),
        "4" => Yii::t('yii', '单台套科学仪器设备'),
        "5" => Yii::t('yii', '海关监管信息'),
        "6" => Yii::t('yii', '服务记录'),
        "7" => Yii::t('yii', '服务成效'),
    ],
    'Login_Status' => [
        '0' => '普通用户',
        '1' => '管理员',
    ],
    'Instrument_Fields' => [
        'innerId' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '仪器内部编码',
            'desc' => '所在单位仪器内部编码	仪器所在单位系统内部id，能唯一标识仪器',
            'support' => ['1', '2', '3', '4'],
            'columns' => ['1', '2', '3', '4'],
            //'required' => true,
        ],
        'image' => [
            'type' => 'URL',
            'length' => 150,
            'label' => '仪器中心图片',
            'desc' => '科学仪器中心图片对应的URL（外网可以访问的图片url），图片要求1M字节以内，jpg格式',
            'support' => ['1', '2', '3', '4'],
            'columns' => ['1', '2', '3',],
        ],
        'level' => [
            'type' => 'VARCHAR',
            'length' => 10,
            'label' => '仪器中心级别',
            'desc' => '国家级、省部级、地市级或单位级等（单选，以所属最高级别为准）',
            'values' => ['国家级', '省部级', '地市级', '单位级', 'other',],
            'support' => ['1', '3',],
            'columns' => ['1', '3',],
        ],
        'cname' => [
            'type' => 'VARCHAR',
            'length' => 50,
            'label' => '仪器中心名称',
            'desc' => '科学仪器中心全称，不可简写（最多50字）',
            'support' => ['2', '3', '4'],
            'columns' => ['4'],
        ],
        'ename' => [
            'type' => 'VARCHAR',
            'support' => ['2', '3', '4'],
        ],
        'instrBelongsType' => [
            'type' => 'SELECT',
            'label' => '隶属关系',
            'desc' => '所属大型科学装置/仪器中心/服务单元	仪器设备所隶属的科学仪器中心',
            'values' => ['大型科学装置', '服务单元', '无',],
            'support' => ['3', '4'],
        ],
        'InstrBelongsName' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '隶属仪器所在单位仪器内部编号',
            'desc' => '确定隶属大型科学装置/仪器中心/服务单元唯一的一台仪器',
            'support' => ['3', '4'],
        ],
        'instrCategory' => [
            'type' => 'VARCHAR',
            'length' => 6,
            'label' => '设备分类编码',
            'desc' => '依据“大型科学仪器设备资源的建设与整合”平台建设项目的《大型科学仪器设备分类标准与编码规则（试用）》，按大类、中类、小类选择填写（6位数字代码）',
            'innerType' => 'number',
            'support' => ['3', '4'],
        ],
        'instrSource' => [
            'type' => 'SELECT',
            'label' => '仪器设备来源',
            'values' => ['购置', '研制', '赠送', '其他',],
            'support' => ['3', '4'],
        ],
        'instrSupervise' => [
            'type' => 'SELECT',
            'label' => '海关监管情况',
            'desc' => '仪器是否被海关监管，若仪器被海关监管，填写“是”，若仪器不被海关监管，填写“否”',
            'values' => ['是', '否',],
            'support' => ['3', '4'],
        ],
        'url' => [
            'type' => 'URL',
            'length' => 100,
            'support' => ['1', '2', '3',],
        ],
        'worth' => [
            'type' => 'FLOAT',
            'label' => '原值',
            'desc' => '科学装置的购置单价或研制成本，按资产登记价格填写。国产科学装置以人民币填报，进口科学装置根据建账时的汇率折合成人民币计算（单位为万元，保留2位小数），优惠价及赠送仪器按市场价或资产登记价格填写',
            'decimal' => 2,
            'unit' => '万元',
            'support' => ['2', '3', '4'],
        ],
        'establish' => [
            'type' => 'DATE',
            'format' => 'yyyy-mm-dd',
            'support' => ['1', '3'],
        ],
        'nation' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '产地国别',
            'desc' => '科学装置的实际制造地所在国家或地区，按国家标准《世界各国和地区名称代码》（GB/T 2659-2000）选择填写，自主研发的填写中国；国家简称',
            'support' => ['2', '3', '4'],
            'columns' => ['4'],
        ],
        'manufacturer' => [
            'type' => 'VARCHAR',
            'length' => 100,
            'label' => '生产制造商',
            'desc' => '仪器设备生产或设计制造单位的全称（非代理商），自主研发需填写本单位（最多100字）',
            'support' => ['3', '4'],
        ],
        'beginDate' => [
            'type' => 'DATE',
            'label' => '启用日期',
            'desc' => '科学装置投入使用的日期（按YYYY-MM-DD格式填写）',
            'format' => 'yyyy-mm-dd',
            'support' => ['2', '3', '4'],
        ],
        'type' => [
            'type' => 'SELECT',
            'values' => ['通用', '专用',],
            'length' => 10,
            'label' => '科学仪器中心类别',
            'desc' => '通用或专用',
            'support' => ['1', '2', '3', '4'],
        ],
        'instrVersion' => [
            'type' => 'VARCHAR',
            'length' => 100,
            'label' => '规格型号',
            'desc' => '按仪器设备生产制造厂商的标识填写',
            'support' => ['3', '4'],
        ],
        'technical' => [
            'type' => 'TEXT',
            'length' => 500,
            'label' => '主要线站与仪器设备及技术指标',
            'desc' => '构成科学装置的核心线站、主要仪器设备的名称、型号以及能代表仪器设备主要技术性能的指标或参数',
            'support' => ['2', '3', '4'],
        ],
        'function' => [
            'type' => 'TEXT',
            'length' => 300,
            'label' => '主要功能',
            'desc' => '对科学装置主要功能的简要介绍',
            'support' => ['3', '4'],
        ],
        'subject' => [
            'type' => 'VARCHAR',
            'length' => 200,
            'label' => '主要学科领域',
            'desc' => '按国家标准《学科分类与代码》（GB/T 13745-2009）选择填写仪器中心支持科技活动的主要学科名称，涉及多个学科领域的可多选（最多4个）（一级学科）\n如：化学，物理学',
            'support' => ['1', '2', '3', '4'],
        ],
        'serviceContent' => [
            'type' => 'VARCHAR',
            'length' => 200,
            'label' => '服务内容',
            'desc' => '科学仪器中心提供的各类服务项目描述，如样品测试、分析检测、技术咨询、认证服务等',
            'support' => ['1', '2', '3',],
        ],
        'achievement' => [
            'type' => 'TEXT',
            'length' => 45,
            'label' => '服务的典型成果',
            'desc' => '列举该科学仪器中心面向社会提供服务、支撑重大项目或主要成果的典型案例（1-3个，没有可填写无）',
            'support' => ['1', '2', '3', '4'],
        ],
        'status' => [
            'type' => 'VARCHAR',
            'length' => 10,
            'label' => '运行状态',
            'desc' => '指科学装置当年通常技术性能状态，按正常、待机、远程服务中、偶有故障、故障频繁、待修、待报废选择填写（单选）。按科学装置当年一般状况下的运行状态填写，并非填报时的特定状态',
            'support' => ['2', '3', '4'],
        ],
        'requirement' => [
            'type' => 'TEXT',
            'length' => 500,
            'label' => '对外开放共享规定',
            'desc' => '用户申请条件、申请方式、申请时间、申请流程、申请材料、服务时间安排等的方面的要求',
            'support' => ['1', '2', '3', '4'],
        ],
        'fee' => [
            'type' => 'TEXT',
            'length' => 500,
            'label' => '参考收费标准',
            'desc' => '对外开放相关收费标准，为用户提供服务时收取的费用，按照单位已有收费标准填写。是对仪器中心现有收费标准的概述，无需精确到每台仪器',
            'support' => ['1', '2', '3', '4'],
        ],
        'serviceUrl' => [
            'type' => 'VARCHAR',
            'length' => 150,
            'label' => '预约服务网址',
            'desc' => '管理单位在线服务平台提供的用户在线预约获取服务接口的URL，能够实现对本仪器中心仪器的预约申请',
            'support' => ['1', '2', '3', '4'],
        ],
        'province' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '详细地置 省',
            'desc' => '科学装置所在的详细地理位置 （自治区、直辖市）',
            'support' => ['1', '2', '3', '4'],
        ],
        'city' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '详细地置 市',
            'desc' => '科学装置所在的详细地理位置',
            'support' => ['1', '2', '3', '4'],
        ],
        'county' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '详细地置  区',
            'desc' => '科学装置所在的详细地理位置（县)',
            'support' => ['1', '2', '3', '4'],
        ],
        'street' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '详细地置 街道',
            'desc' => '科学装置所在的详细地理位置（乡镇，需包括街道/乡镇门牌号）',
            'support' => ['1', '2', '3', '4'],
        ],
        'contact' => [
            'type' => 'VARCHAR',
            'length' => 20,
            'label' => '联系人',
            'desc' => '联系人姓名',
            'support' => ['1', '2', '3', '4'],
        ],
        'phone' => [
            'type' => 'PHONE',
            'label' => '电话',
            'desc' => '座机（加区号）或手机，以联系人座机为主，一个电话号码即可',
            'support' => ['1', '2', '3', '4'],
        ],
        'email' => [
            'type' => 'EMAIL',
            'label' => '电子邮箱',
            'desc' => '联系人的电子邮箱',
            'support' => ['1', '2', '3', '4'],
        ],
        'address' => [
            'type' => 'VARCHAR',
            'length' => 100,
            'label' => '通讯地址',
            'desc' => '通讯地址',
            'support' => ['2', '3', '4'],
        ],
        'postalcode' => [
            'type' => 'VARCHAR',
            'length' => 6,
            'label' => '邮政编码',
            'desc' => '联系人办公地址的邮政编码',
            'innerType' => 'number',
            'support' => ['1', '2', '3', '4'],
        ],
        'shareMode' => [
            'type' => 'SELECT',
            'label' => '共享模式',
            'values' => ['内部共享', '外部共享', '不共享',],
            'support' => ['1', '2', '3', '4'],
        ],
        'auditStatus' => [
            'type' => 'SELECT',
            'label' => '提交状态',
            'desc' => '未提交，代表后期需要对数据进行重复报，更新完善数据；提交，代表报送的数据无误，后期无需更新完善。已经提交的数据，再次推送更新无效，需等待后期审核驳回再进行修改。\n如果因为失误提交，请等待国家平台审核驳回后更新',
            'values' => ['-1' => '未提交', '0' => '提交',],
            'showValue' => true,
            'support' => ['1', '2', '3', '4'],
        ],
    ],
    'Service_Record' => [
        'innerId' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '所在单位仪器内部编号',
            'desc' => '管理单位资产管理部门赋予该仪器设备唯一编号',
            'column' => true
        ],
        'amounts' => [
            'type' => 'FLOAT',
            'label' => '服务金额',
            'desc' => '实际服务的总额，以元为单位',
            'decimal' => 2,
            'unit' => '万元',
            'column' => true,
        ],
        'serviceTime' => [
            'type' => 'DATE',
            'format' => 'yyyy-mm-dd',
            'label' => '实际服务时间',
            'desc' => '科研设施与仪器向用户实际提供服务的日期或时间段',
        ],
        'serviceContent' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '实际服务内容',
            'desc' => '科研设施与仪器向用户实际提供的服务项目，如样品测试、分析检测等，最多200字',
        ],
        'serviceWay' => [
            'type' => 'SELECT',
            'values' => ['占用共享', '技术共享', '委托共享', '远程共享', '其他（可多选）'],
            'length' => 15,
            'label' => '服务方式',
            'desc' => '一是占用共享，即服务客体(需求者)按一定规程自行操作使用；二是技术共享，即在服务主体的技术指导下，服务客体有限度地自主使用操作仪器设备；三是委托共享，即受服务客体委托，由服务主体按要求启动和运行仪器设备，并向委托方提交相应结果；四是远程共享；五是其他（可多选）',
        ],
        'serviceAmount' => [
            'type' => 'VARCHAR',
            'length' => 10,
            'label' => '服务量',
            'desc' => '根据订单，科研设施与仪器所提供的服务量，根据仪器类型和服务方式的不同，可按所占用的时长或次数（包含必要开机准备时间、测试时间和必须的后处理时间，不包括空载运行的时间，计量单位为小时）、样品测试数量、分析检测数量、技术指导次数等该领域统计方法计算。',]
        ,
        'subjectName' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '课题名称',
            'desc' => '用户利用科研设施与仪器所支撑的课题名称（没有则填写“无”）',
            'column' => true,
        ],
        'subjectIncome' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '课题经费来源',
            'desc' => '课题最主要的经费来源，可多选（最多4个）：\nA 国家重大科技专项；B 国家自然科学基金；C 863计划；D 国家科技支撑（攻关）计划；E 火炬计划；F 星火计划；G 973计划；H 211工程；I 985工程；J 公益性行业科研专项；K 国家社会科学基金；L 国家科技基础性工作专项；M 科技基础条件平台专项；N 除上述国家计划外由中央政府部门下达的课题；O 地方科技计划项目；P 其他\n例：863计划',
        ],
        'subjectArea' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '课题主要学科领域',
            'desc' => '用户申请机时进行研究的课题所属的主要学科领域，按国家标准《学科分类与代码》（GB/T 13745-2009）选择填写主要学科名称，涉及多个学科领域的可多选（最多4个，一级学科）\n力学，数学,化学',
        ],
        'subjectContent' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '课题研究内容',
            'desc' => '用户利用科研设施与仪器所研究的课题的基本内容概述（最多200字）（没有则填写“无”）',
        ],
        'applicant' => [
            'type' => 'VARCHAR',
            'length' => 20,
            'label' => '申请人',
            'desc' => '	请人的姓名（最多20字）',
        ],
        'applicatPhone' => [
            'type' => 'VARCHAR',
            'length' => 20,
            'label' => '申请人电话',
            'desc' => '申请人的电话号码，座机（加区号）或手机（最多20字）以座机为主',
        ],
        'applicatEmail' => [
            'type' => 'VARCHAR',
            'length' => 50,
            'label' => '申请人电子邮箱',
            'desc' => '请人的电子邮箱（最多50字）',
        ],
        'applicatUnit' => [
            'type' => 'VARCHAR',
            'length' => 50,
        ],
        'comment' => [
            'type' => 'VARCHAR',
            'length' => 10,
            'label' => '用户评价及意见',
            'desc' => '用户对本次服务的评价，非常满意、基本满意、一般、不满意、极差（单选）。具体的意见和建议',
        ],
        'auditStatus' => [
            'type' => 'SELECT',
            'label' => '提交状态',
            'desc' => '未提交，代表后期需要对数据进行重复报，更新完善数据；提交，代表报送的数据无误，后期无需更新完善。已经提交的数据，再次推送更新无效，需等待后期审核驳回再进行修改。\n如果因为失误提交，请等待国家平台审核驳回后更新',
            'values' => ['-1' => '未提交', '0' => '提交',],
            'showValue' => true,
            'support' => ['1', '2', '3',],
        ],
    ],
    'Service_Effect' => [
        'submittedRates' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '科研设施与仪器入网比例',
            'desc' => '指该管理单位在国家网络管理平台注册填报的科研设施与仪器占符合申报条件的全部科研设施与仪器的比例，体现了纳入国家网络管理平台的情况',
            'column' => true
        ],
        'activatedRates' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '正常运行设备比例',
            'desc' => '纳入国家网络管理平台的科研设施与仪器正常运行的数量占纳入的全部科研设施与仪器数量的比例',
            'column' => true,
        ],
        'totalShareRates' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '参与共享比例',
            'desc' => '指参与共享（包括内部共享和外部共享两种方式）的科研设施与仪器和全部符合共享条件科研设施与仪器的数量之比，体现了总体开放共享服务的情况',
            'column' => true,
        ],
        'externalShareRates' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '外部共享比例',
            'desc' => '指提供对外服务的科研设施与仪器占全部符合共享条件的科研设施与仪器的比例，体现了对外开放共享服务的比例情况',
            'column' => true,
        ],
        'Innovation' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '仪器创新开发',
            'desc' => '管理单位仪器功能开发、新技术和新方法的研究、仪器设备功能的升级改造、仪器研究能力、科研设施与仪器自主创新研发能力的情况及数量（最多500字）',
        ],
        'serviceAmounts' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '服务总量',
            'desc' => '科研设施与仪器对外提供服务的总量，根据仪器类型和服务方式的不同，包括设备机时服务、样品测试数量、分析检测服务、培训等（最多200字）',
        ],
        'user' => [
            'type' => 'VARCHAR',
            'length' => 45,
            'label' => '用户类型及数量',
            'desc' => '	科研设施与仪器服务用户的类型及数量（单位：人/次）',
        ],
        'Project' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '支撑项目',
            'desc' => '科研设施与仪器对外服务，用户完成的各种科研项目或合作项目数的数量，特别是服务各级各类科技计划（专项、基金、重大工程）等情况（最多200字）',
        ],
        'Thesis' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '支撑论文',
            'desc' => '用户利用科研设施与仪器所产生的论文数量，包括已公开发表的论文，或者尚未正式发表但已被录用的论文，特别是在三大检索SCI、EI、ISTP发表的论文，最多200字',
        ],
        'Book' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '支撑论著',
            'desc' => '用户利用科研设施与仪器所产生的论著或专著数量（最多200字）',
        ],
        'Report' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '支撑科技报告',
            'desc' => '用户利用科研设施与仪器所产生的科技报告数量（最多200字）',
        ],
        'Patent' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '支撑发明专利',
            'desc' => '用户利用科研设施与仪器所产生的发明专利的数量，指已授权发明专利数，不含实用新型和外观设计（最多200字）',
        ],
        'Output' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '产出科学数据',
            'desc' => '用户使用科研设施与仪器过程中产生的原始数据及研究分析数据，包括调查观测、测试化验、实验研究等相关科学数据（最多200字）',
        ],
        'Achievements' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '科技成果及获奖情况',
            'desc' => '使用科研设施与仪器产生的科技成果及获奖成果数量（最多200字）',
        ],
        'serviceIncome' => [
            'type' => 'TEXT',
            'length' => 45,
            'label' => '对外服务收入',
            'desc' => '管理单位科研设施与仪器对外服务获得的收入，以人民币计算（单位万元，保留小数点后两位）。包括科研设施与仪器对外提供服务收入的测试费、租赁收入和其他服务收入等',
        ],
        'socialBenefit' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '社会效益',
            'desc' => '科研设施与仪器对外开放共享所产生的社会效益，如服务重大工程、企业创新、服务民生、应急事件、科学普及、政府决策、其他等情况（最多500字）',
        ],
        'Remark' => [
            'type' => 'TEXT',
            'length' => 200,
            'label' => '其他成果',
            'desc' => '非上述成果之外的成果（最多200字）',
        ],
    ]

];
